# Generated by Django 2.2.4 on 2019-08-16 10:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafeapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserve',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 16, 14, 30, 41, 64991)),
        ),
    ]
